- name: Create spring boot job
  jenkins_job:
   config: "{{ lookup('file', 'templates/config.xml')}}"
   name: spring-boot
   username: admin
   password: '@/var/lib/jenkins/secrets/initialAdminPassword'
   url: http://10.0.0.4:8080
