Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 8080, host: 80
  config.vm.network "forwarded_port", guest: 8082, host: 8080

  config.vm.provision "shell" do |s|
    s.path = "initScript.sh"
    end
end