Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 8080, host: 801
  config.vm.network "forwarded_port", guest: 8091, host: 8082

  config.vm.provision "shell" do |s|
    s.path = "init.sh"
    end
end